[Terminals]
Alacritty | alacritty | cask
Ghostty | ghostty | cask
iTerm2 | iterm2 | cask

[IDEs]
Antigravity | antigravity | cask
VS Codium | vscodium | cask
Zed | zed | cask

[Coding Agents]
Gemini CLI | gemini-cli | formula
OpenCode | anomalyco/tap/opencode | formula
Claude Code | claude-code | cask
Codex | codex | cask

[Browsers]
Brave | brave-browser | cask
Firefox | firefox | cask
Google Chrome | google-chrome | cask
Orion Browser | orion | cask

[Utilities]
Htop | htop | formula
Password generator | pwgen | formula
Tig | tig | formula
Tree | tree | formula
Watch | watch | formula
Flycut | flycut | cask
Rectangle | rectangle | cask
Zoom | zoom | cask
